server.port=8086
spring.application.name=gateway-service

backend.base-url=http://localhost:8085
security.jwt.secret=12345678901234567890123456789012

# PUBLIC
rate.limit.public.max-requests=5
rate.limit.public.window-seconds=60

# PRIVATE
rate.limit.private.max-requests=10
rate.limit.private.window-seconds=60